const bcrypt = require('bcryptjs');
const User = require('../../models/User');

const PAGE_SIZE_MAX = 100;

const normalisePage = (value, fallback = 1) => {
  const num = parseInt(value, 10);
  if (!Number.isFinite(num) || num <= 0) return fallback;
  return num;
};

const normalisePageSize = (value, fallback = 10) => {
  const num = parseInt(value, 10);
  if (!Number.isFinite(num) || num <= 0) return fallback;
  return Math.min(PAGE_SIZE_MAX, num);
};

exports.listMembers = async (req, res) => {
  try {
    const page = normalisePage(req.query.page, 1);
    const pageSize = normalisePageSize(req.query.pageSize, 10);
    const q = (req.query.q || '').trim();
    const status = (req.query.status || '').trim().toLowerCase();

    const result = await User.list({ page, pageSize, q, status });
    res.json({
      data: result.data,
      total: result.total,
    });
  } catch (error) {
    console.error('listMembers error:', error);
    res.status(500).json({ message: 'Failed to load members' });
  }
};

exports.getMemberById = async (req, res) => {
  try {
    const member = await User.findById(req.params.id);
    if (!member) {
      return res.status(404).json({ message: 'Member not found' });
    }
    res.json({ member });
  } catch (error) {
    console.error('getMemberById error:', error);
    res.status(500).json({ message: 'Failed to load member' });
  }
};

exports.updateMemberStatus = async (req, res) => {
  try {
    const { status } = req.body || {};
    const normalizedStatus = (status || '').trim().toLowerCase();
    if (!User.VALID_STATUSES.includes(normalizedStatus)) {
      return res.status(400).json({ message: 'Invalid status' });
    }

    const updated = await User.updateStatus(req.params.id, normalizedStatus);
    if (!updated) {
      return res.status(404).json({ message: 'Member not found' });
    }

    res.json({
      memberId: Number(req.params.id),
      status: normalizedStatus,
    });
  } catch (error) {
    console.error('updateMemberStatus error:', error);
    res.status(500).json({ message: 'Failed to update status' });
  }
};

const generatePassword = (length = 10) => {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789!@#$%^&*';
  let result = '';
  for (let i = 0; i < length; i += 1) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

exports.resetMemberPassword = async (req, res) => {
  try {
    let { password } = req.body || {};
    password = (password || '').trim();
    const autoGenerated = password === '';

    if (!password) {
      password = generatePassword();
    } else if (password.length < 6) {
      return res.status(400).json({ message: 'Password must be at least 6 characters' });
    }

    const hash = await bcrypt.hash(password, 10);
    const updated = await User.updatePassword(req.params.id, hash);
    if (!updated) {
      return res.status(404).json({ message: 'Member not found' });
    }

    res.json({
      memberId: Number(req.params.id),
      newPassword: password,
      generated: autoGenerated,
    });
  } catch (error) {
    console.error('resetMemberPassword error:', error);
    res.status(500).json({ message: 'Failed to reset password' });
  }
};

exports.deleteMember = async (req, res) => {
  try {
    const deleted = await User.delete(req.params.id);
    if (!deleted) {
      return res.status(404).json({ message: 'Member not found' });
    }
    res.status(204).send();
  } catch (error) {
    console.error('deleteMember error:', error);
    res.status(500).json({ message: 'Failed to delete member' });
  }
};
