const mysql = require('mysql2/promise');
const dotenv = require('dotenv');
const path = require('path');
const fs = require('fs');

dotenv.config({ path: path.join(__dirname, '.env') });

const OUTPUT_FILE = path.join(__dirname, '../rmutk (4).sql');

async function fullDump() {
    const pool = mysql.createPool({
        host: process.env.DB_HOST,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_NAME,
        port: process.env.DB_PORT || 3306,
        multipleStatements: true,
        dateStrings: true // Keep dates as strings to avoid JS Date conversion issues
    });

    try {
        let dump = `-- MySQL Full Dump generated by Agent
-- Host: ${process.env.DB_HOST}    Database: ${process.env.DB_NAME}
-- ------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

`;

        const [tables] = await pool.query("SHOW TABLES");
        const tableNames = tables.map(t => Object.values(t)[0]);

        for (const tableName of tableNames) {
            console.log(`Dumping table: ${tableName}`);

            // Structure
            dump += `\n-- Table structure for table \`${tableName}\`\n`;
            dump += `DROP TABLE IF EXISTS \`${tableName}\`;\n`;

            const [createRes] = await pool.query(`SHOW CREATE TABLE \`${tableName}\``);
            dump += `${createRes[0]['Create Table']};\n`;

            // Data
            dump += `\n-- Dumping data for table \`${tableName}\`\n`;
            dump += `LOCK TABLES \`${tableName}\` WRITE;\n`;
            dump += `/*!40000 ALTER TABLE \`${tableName}\` DISABLE KEYS */;\n`;

            const [rows] = await pool.query(`SELECT * FROM \`${tableName}\``);
            if (rows.length > 0) {
                const inserts = [];
                for (const row of rows) {
                    const values = Object.values(row).map(val => {
                        if (val === null) return 'NULL';
                        if (typeof val === 'number') return val;
                        // Escape strings basic
                        let str = String(val)
                            .replace(/\\/g, '\\\\')
                            .replace(/'/g, "\\'")
                            .replace(/\n/g, '\\n')
                            .replace(/\r/g, '\\r')
                            .replace(/\x00/g, '\\0');
                        return `'${str}'`;
                    });
                    inserts.push(`(${values.join(',')})`);
                }
                dump += `INSERT INTO \`${tableName}\` VALUES ${inserts.join(',')};\n`;
            }

            dump += `/*!40000 ALTER TABLE \`${tableName}\` ENABLE KEYS */;\n`;
            dump += `UNLOCK TABLES;\n`;
        }

        dump += `\n/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
`;

        fs.writeFileSync(OUTPUT_FILE, dump, 'utf8');
        console.log(`Dump saved to ${OUTPUT_FILE}`);

    } catch (err) {
        console.error('Dump failed:', err);
    } finally {
        await pool.end();
    }
}

fullDump();
